### ISSUE TITLE
Design User Flows

### ISSUE THREAD

**Issue by MasterPi-2124** [MasterPi-2124/CNWeb-30#3]
- [x] Nga
 - [x] Nghĩa
 - [x] Ngọc

**Comment by Nelly502** [comment]
Phân tích chức năng chi tiết của tác tử sinh viên và biểu diễn trình tự hệ thống qua các biểu đồ tuần tự [https://husteduvn-my.sharepoint.com/:w:/g/personal/nga_ptp200430_sis_hust_edu_vn/ETcRShs8iw1DhFd7jP3sSqwBzWAJ00Oc6eh4x8_QzLTcJA?e=Kj4sFd](https://github.com/users/MasterPi-2124/projects/1/views/url)

**Comment by NgocJQK** [comment]
[](url)

**Comment by NgocJQK** [comment]
Usecase, Activity, Sequence Admin
